services:
  crop-wizard-db:
    container_name: crop-wizard-db
    image: postgres:14.0
    restart: always
    ports:
      - '6767:5432'
    env_file:
      - .env
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
